### ISSUE TITLE
cara add akun

### ISSUE THREAD

**Issue by kerjaairdrop43** [faiqxid/supermeow_tele_bot#2]
gimana cara add akunnya bang

**Comment by faiqxid** [comment]
Udah bisa? Atu gimana?

**Comment by kerjaairdrop43** [comment]
> Udah bisa? Atu gimana?



> Udah bisa? Atu gimana?



> Udah bisa? Atu gimana?

dah bang

**Comment by kerjaairdrop43** [comment]
> Udah bisa? Atu gimana?



> Udah bisa? Atu gimana?



> Udah bisa? Atu gimana?

punya sc wcoin ga bang

**Comment by faiqxid** [comment]
Dm tele ae lah bro masa chat an di sini bjir agak lain -_-
@idFaiq
